### ISSUE TITLE
SingleIntensityAccumulationError:

### ISSUE THREAD

**Issue by potis** [loli/medpy#21]
Hi, I am trying to use the IntensityRangeStandardization function however I am running to the following issue:

> medpy.filter.IntensityRangeStandardization.SingleIntensityAccumulationError: Image no.0 shows an unusual single-intensity accumulation that leads to a situation where two percentile values are equal. This situation is usually caused, when the background has not been removed from the image. Another possibility would be to reduce the number of landmark percentiles landmarkp or to change their distribution.

I am trying to understand what exactly you mean by " background has not been removed from the image"

For instance in the following code I get the same error:

```
import numpy
from medpy.filter import IntensityRangeStandardization
base_image = numpy.asarray([[0,0,0],[3,5,4],[7,8,9],[2,4,8]])
good_trainingset = [base_image + x for x in range(10)]

print base_image.dtype
print type(good_trainingset)
print good_trainingset

irs = IntensityRangeStandardization(cutoffp=(1, 99), landmarkp=[10, 20, 30, 40, 50, 60, 70, 80, 90], stdrange='auto')
irs.train_transform(good_trainingset,surpress_mapping_check=True)

print its

```
Output

```
int64
<type 'list'>
[array([[0, 0, 0],
       [3, 5, 4],
       [7, 8, 9],
       [2, 4, 8]]), array([[ 1,  1,  1],
       [ 4,  6,  5],
       [ 8,  9, 10],
       [ 3,  5,  9]]), array([[ 2,  2,  2],
       [ 5,  7,  6],
       [ 9, 10, 11],
       [ 4,  6, 10]]), array([[ 3,  3,  3],
       [ 6,  8,  7],
       [10, 11, 12],
       [ 5,  7, 11]]), array([[ 4,  4,  4],
       [ 7,  9,  8],
       [11, 12, 13],
       [ 6,  8, 12]]), array([[ 5,  5,  5],
       [ 8, 10,  9],
       [12, 13, 14],
       [ 7,  9, 13]]), array([[ 6,  6,  6],
       [ 9, 11, 10],
       [13, 14, 15],
       [ 8, 10, 14]]), array([[ 7,  7,  7],
       [10, 12, 11],
       [14, 15, 16],
       [ 9, 11, 15]]), array([[ 8,  8,  8],
       [11, 13, 12],
       [15, 16, 17],
       [10, 12, 16]]), array([[ 9,  9,  9],
       [12, 14, 13],
       [16, 17, 18],
       [11, 13, 17]])]
Traceback (most recent call last):
  File "testdelet.py", line 32, in <module>
    irs.train_transform(good_trainingset,surpress_mapping_check=True)
  File "build/bdist.linux-x86_64/egg/medpy/filter/IntensityRangeStandardization.py", line 345, in train_transform
  File "build/bdist.linux-x86_64/egg/medpy/filter/IntensityRangeStandardization.py", line 260, in train
  File "build/bdist.linux-x86_64/egg/medpy/filter/IntensityRangeStandardization.py", line 436, in __compute_stdrange
medpy.filter.IntensityRangeStandardization.SingleIntensityAccumulationError: Image no.0 shows an unusual single-intensity accumulation that leads to a situation where two percentile values are equal. This situation is usually caused, when the background has not been removed from the image. Another possibility would be to reduce the number of landmark percentiles landmarkp or to change their distribution.
```

The same happens when i set : 

`
base_image = numpy.asarray([[1,1,1],[3,5,4],[7,8,9],[2,4,8]])
`

Thank you.

**Comment by loli** [comment]
Dear potis,

the intensity standardization algorithm works by mapping the provided images to a common scale according to anchor points in their respective histograms. You provide a number of very small images (each on 12 values) with a rather hight number of landmark points (the anchor points).

The border anchor points are determined by your cutoff percentiles

  `numpy.array(numpy.percentile(good_trainingset[0], (1, 99)))`

resulting in the anchor points

  `[ 0.  ,  8.89]`

In between these two, nine further anchor points are set

  `numpy.array(numpy.percentile(good_trainingset[0], [10, 20, 30, 40, 50, 60, 70, 80, 90]))`


which leads to

  `array([ 0. ,  0.4,  2.3,  3.4,  4. ,  4.6,  6.4,  7.8,  8. ])`

As you can readily see, the left-most anchor point `0.` and the subsequent one `0.` fall onto the same value since `good_trainingset[0]` contains three zeros. Defining a linear connection between these would result in a slope of either zero or infinity, both of which are not a good idea. Therefore the error.

Using nearly as many anchor points as image pixels makes anyway not much sense. If you really must use such small images, look at the second part of error message (_Another possibility would be to reduce the number of landmark percentiles landmarkp or to change their distribution._). This

  `irs = IntensityRangeStandardization(cutoffp=(1, 99), landmarkp=[25, 50, 75], stdrange='auto')`
  `irs.train_transform(good_trainingset,surpress_mapping_check=True)`

works, for example.


Regarding the background part of the message: MedPy is developed to work with medical images. These scans often have a large, mostly zero-valued background denoting air surrounding the body area scanned. This should be removed before the intensity range standardization. See [here](http://www.nhsdirect.wales.nhs.uk/assets/images/encyclopaedia/MRIscan.jpg) for an example.

I hope this helps you.

Best,
loli
