### ISSUE TITLE
What is 'voxelspacing' ?

### ISSUE THREAD

**Issue by aiosin** [loli/medpy#73]
I've been seeming this term everywhere. Coudln't figure it out, though nothing of it.
I'm rewriting the tamura textural coarseness feature (for my own repo but would like to merge it here) and would like to support whatever you guys understand under the term voxelspacing.

Any ideas ?

**Comment by loli** [comment]
Imagine recording a MRI of a brain. A pixel in the resulting image has a single grey value. But since the image resolution is of course limited, this grey value number represents the average physical attributes of a small area of brain tissue.

The pixel size or spacing denotes the sizes of a single pixel, i.e., the width and height of the physical volume from which it is a representation. This is an important attribute of, e.g., satellite and medical images.

Since medical images are often recorded as volumes, we employ the term voxelspacing in MedPy. Note that MedPy aims to be dimensionality independent, hence voxelspacing can mean a volume arbitrary dimensions.

When working with texture features as in your case, the voxelspacing is important to consider to make the resulting features between images comparable. Coarseness should, for example, be expressed in physical units rather than pixels.


I hope I could help. Looking forward to your contribution!
