### ISSUE TITLE
Scipy 1.1.0 incompatibility _get_output in average_filter in image.py

### ISSUE THREAD

**Issue by 01bui** [loli/medpy#78]
Hi Oskar,

I got an error when I tried to use your medpy.filter.image.ssd. I figured the following:

average_filter in medpy.filter.image is returned 2 values:
`output, return_value = _get_output(output, input)`

Scipy 1.1.0 _get_output only returns 1 value:
```
def _get_output(output, input, shape=None):
    if shape is None:
        shape = input.shape
    if output is None:
        output = numpy.zeros(shape, dtype=input.dtype.name)
    elif type(output) in [type(type), type(numpy.zeros((4,)).dtype)]:
        output = numpy.zeros(shape, dtype=output)
    elif isinstance(output, string_types):
        output = numpy.typeDict[output]
        output = numpy.zeros(shape, dtype=output)
    elif output.shape != shape:
        raise RuntimeError("output shape not correct")
    return output
```
 
I am not sure which scipy version return 2 values but it would be great to update your programs to return 1 value when calling _get_output from Scipy.

Thank you!

**Comment by loli** [comment]
Hi Vy Bui,

thank you for spotting this. It seems that the scipy code changed in March 2018 (https://github.com/scipy/scipy/pull/8461).

For now, I added an additional scipy restriction to the setup.py (#1760d0ed1f5f18647f7f3b242226eed09786b27f). But on the long run, this should be fixed as already version 1.1.0 is old.

Best,
Oskar

**Comment by loli** [comment]
This change of behavior is indeed a problem. It could be handled in three ways, as far as I can see right now:

1. Forbid any version of scipy >= 1.1.0 (not good, because it limits the user, but fast)
2. Change the code to only expect one return value (not good, because older scipy versions become incompatible)
3. Build in a switch checking for the number of returned values (ok, but not too clean)
4. Remove all usages of this function (not sure, but surely the most difficult solution)

**Comment by loli** [comment]
Found some time, decided on option 2. and upped the scipy requirements in the setup.py with commit 5a8fe50
